publish_ami_events: False

ajam:
  host: asterisk-ajam
  port: 5040
  username: xivo_amid
  password: opensesame
  verify_certificate: False

auth:
  host: inexisting-auth-server
  port: 9497

rest_api:
  https:
    certificate: /usr/local/share/xivo-amid-ssl/server.crt
    private_key: /usr/local/share/xivo-amid-ssl/server.key
