sync:
  image: n3llyb0y/wait
  links:
    - amid
    - asterisk-ajam
  environment:
    PORTS: "5040 9491"

amid:
  image: xivo-amid-tests
  ports:
    - "9491:9491"
  volumes:
    - "./etc/xivo-amid:/etc/xivo-amid"
    - "./ssl/asterisk-ajam:/usr/local/share/asterisk-ajam-ssl"
    - "./ssl/localhost:/usr/local/share/xivo-amid-ssl"
    - "../../..:/usr/src/xivo-amid"
  links:
    - "asterisk-ajam"

asterisk-ajam:
  image: p0bailey/docker-flask
  expose:
    - "5040"
  volumes:
    - "./ssl/asterisk-ajam:/usr/local/share/asterisk-ajam-ssl"
    - "./asterisk-ajam:/usr/local/share/asterisk-ajam"
  command: "python /usr/local/share/asterisk-ajam/mock-asterisk-ajam.py 5040"
