version: '3'
services:
  sync:
    depends_on:
      - amid
      - auth
    environment:
      TARGETS: "amid:9491 auth:9497"

  amid:
    volumes:
      - "./no_ajam_server/etc/xivo-amid:/etc/xivo-amid"
      - "./no_ajam_server/ssl/asterisk-ajam:/usr/local/share/asterisk-ajam-ssl"
      - "./no_ajam_server/ssl/xivo-auth:/usr/local/share/xivo-auth-ssl"
      - "./no_ajam_server/ssl/localhost:/usr/local/share/xivo-amid-ssl"

  auth:
    volumes:
      - "./no_ajam_server/xivo-auth:/usr/local/share/xivo-auth"
      - "./no_ajam_server/ssl/xivo-auth:/usr/local/share/xivo-auth-ssl"
