version: '3'
services:
  sync:
    image: wazopbx/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  amid:
    image: wazo-amid-tests
    ports:
      - "9491"
    volumes:
      - "../..:/usr/src/wazo-amid"
      - "./ssl/wazo-auth:/usr/local/share/wazo-auth-ssl"
      - "./ssl/localhost:/usr/local/share/wazo-amid-ssl"
      - "./etc/wazo-amid/conf.d/disable-ami-events.yml:/etc/wazo-amid/conf.d/disable-ami-events.yml"
      - "./etc/wazo-amid/conf.d/ajam.yml:/etc/wazo-amid/conf.d/ajam.yml"
      - "./etc/wazo-amid/conf.d/auth.yml:/etc/wazo-amid/conf.d/auth.yml"
      - "./etc/wazo-amid/conf.d/rest-api.yml:/etc/wazo-amid/conf.d/rest-api.yml"

  asterisk-ajam:
    image: p0bailey/docker-flask
    ports:
      - "5040"
    volumes:
      - "./ssl/asterisk-ajam:/usr/local/share/asterisk-ajam-ssl"
      - "./asterisk-ajam:/usr/local/share/asterisk-ajam"
    command: "python /usr/local/share/asterisk-ajam/mock-asterisk-ajam.py 5040"

  auth:
    image: p0bailey/docker-flask
    expose:
      - "9497"
    volumes:
      - "./wazo-auth:/usr/local/share/wazo-auth"
      - "./ssl/wazo-auth:/usr/local/share/wazo-auth-ssl"
    command: "python /usr/local/share/wazo-auth/mock-wazo-auth.py 9497"
